# Generated by Django 5.2.12 on 2026-03-25 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_alter_lignebonreception_prix_ht_and_more'),
        ('produits', '0002_produit_p_achat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignebonreception',
            old_name='bon',
            new_name='bon_reception',
        ),
        migrations.AlterField(
            model_name='lignebonreception',
            name='prix_ht',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignebonreception',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
    ]
