# Generated by Django 5.2.12 on 2026-03-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignebonlivraison',
            old_name='bonlivraison',
            new_name='bon_livraison',
        ),
    ]
