# Generated by Django 5.2.12 on 2026-03-25 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_rename_bonlivraison_lignebonlivraison_bon_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonlivraison',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
