# Generated by Django 5.2.12 on 2026-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_alter_bonlivraison_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonlivraison',
            name='est_facture',
            field=models.BooleanField(default=False),
        ),
    ]
