# Generated by Django 5.2.12 on 2026-03-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_bonlivraison_est_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonlivraison',
            name='est_facture',
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.facture'),
        ),
    ]
