# Generated by Django 5.2.11 on 2026-03-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_adresse'),
        ('produits', '0001_initial'),
        ('ventes', '0005_facture_base_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('mf_client', models.CharField(blank=True, max_length=50)),
                ('adresse_client', models.CharField(blank=True, max_length=255)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.devis')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
        ),
    ]
