# Generated by Django 5.2.11 on 2026-03-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_devis_lignedevis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='total_ttc',
        ),
    ]
