# Generated by Django 5.2.11 on 2026-03-13 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_adresse'),
        ('produits', '0001_initial'),
        ('ventes', '0007_remove_devis_total_ttc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('mf_client', models.CharField(blank=True, max_length=30)),
                ('adresse_client', models.CharField(blank=True, max_length=200)),
                ('telephone_client', models.CharField(blank=True, max_length=30)),
                ('email_client', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée')], default='brouillon', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_rem', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_ht', models.DecimalField(decimal_places=3, max_digits=10)),
                ('taux_rem', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.bonlivraison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
